#!/usr/bin/env bash
# Configuring an NGINX server to nlisten to port 80


# Removing the default NGINX configuration file
rm /etc/nginx/sites-enabled/default

# Configuring NGINX to listen to port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restarting NGINX
service nginx restart
