#!/usr/bin/env bash
# Displays Best School except the 4th and 8th line

i=1
while [ $i" -le 10 ]
do
	if [ "$i" -eq 4 ]
		echo "bad luck"
	elif [ "$i" -eq 8 ]
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$[i+1]
done
