#!/usr/bin/env bash
# Displays Best School except the 4th and 8th line

i=0
while [ $i" -le 9 ]
do
	if [ "$i" -eq 3 ]
		echo "bad luck"
	elif [ "$i" -eq 7 ]
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$[i+1]
done
